#! /usr/bin/python

""" cadmin is the administrative program that performs online tasks.

For now, that consists of creating new channels, adding single rpms
(new errata) to existing channels, etc.

This software is distributed under the GPL v2, see file "LICENSE"
Copyright 2001, 2002   Hunter Matthews  <thm@duke.edu>

"""

# We cheat like we've never cheated before... 
# we steal up2dates network code itself.
# this gives us relatively easy network code
# unfortunately, it ties us far more closely to up2date internals

# Configured module dir
# These are replaced by make, so beware
MODULES_DIR="/usr/share/current"

import sys
sys.path.append(MODULES_DIR)
sys.path.append('/usr/share/rhn')

# Grab the network code from up2date itself.
from up2date_client import rpcServer

# don't import config - might not be running on a machine with current.conf
# don't import logger - same reasoning

# Just hard code this monkey
# Its the one for current anyway...
rhns_ca_cert = '/usr/share/rhn/RHNS-CA-CERT'

def main():
    server = rpcServer.getServer()
    server.use_CA_chain(rhns_ca_cert)

    result = rpcServer.doCall(server.current.hello, 'hunter', 'matthews')

    print result

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print "Interupted by user command"
    
## END OF LINE ##    
